--- 
- hosts: routers
  gather_facts: false
  connection: network_cli
  become_method: enable

  tasks:
    - name: ACL Configuration for R1 (Denies Faculty Access to DEVASC)
      when: ansible_host == "10.1.1.1"
      ios_config:
        parents: ip access-list standard DENY_ACCESS_TO_DEVASC
        lines: 
          - deny 172.32.1.0 0.0.0.255
          - permit any

    - name: Apply ACL to Interface F0/0
      when: ansible_host == "10.1.1.1"
      ios_config: 
        parents: interface FastEthernet0/0
        lines:
          - ip access-group DENY_ACCESS_TO_DEVASC out
 
    - name: ACL configuration for R3 (Denies Access to ITSO)
      when: ansible_host == "10.1.2.2"
      ios_config:
        parents: ip access-list standard DENY_ACCESS_TO_ITSO
        lines:
          - deny 172.32.1.0 0.0.0.255
          - permit any

    - name: Apply ACL to Interface F0/1
      when: ansible_host == "10.1.2.2"
      ios_config:
        parents: interface FastEthernet0/1
        lines:
          - ip access-group DENY_ACCESS_TO_ITSO out