---
- hosts: routers
  gather_facts: false
  connection: network_cli
  become_method: enable 

  tasks: 
    - name: OSPF configuration for R1
      when: ansible_host == "10.1.1.1"
      ios_config: 
        parents: router ospf 1
        lines: 
          - router-id 3.3.3.3 
          - network 192.168.10.0 0.0.0.255 area 0 
          - network 10.1.1.0 0.0.0.3 area 0 
          - network 10.1.3.0 0.0.0.3 area 0
          - passive-interface FastEthernet0/0 
 
    - name: OSPF configuration for R2
      when: ansible_host == "10.1.1.2"
      ios_config: 
        parents: router ospf 1
        lines: 
          - router-id 6.6.6.6 
          - network 10.1.1.0 0.0.0.3 area 0 
          - network 10.1.2.0 0.0.0.3 area 0
          - default-information originate 
 
    - name: OSPF configuration for R3
      when: ansible_host == "10.1.2.2"
      ios_config: 
        parents: router ospf 1 
        lines: 
          - router-id 9.9.9.9 
          - network 172.32.1.0 0.0.0.255 area 0 
          - network 152.16.1.0 0.0.0.255 area 0 
          - network 10.1.2.0 0.0.0.3 area 0 
          - network 10.1.3.0 0.0.0.3 area 0 
          - passive-interface FastEthernet0/0 
          - passive-interface FastEthernet0/1